"""Added server default

Revision ID: 57887b4ff41c
Revises: f5c963d13750
Create Date: 2016-09-16 16:49:10.976517

"""

# revision identifiers, used by Alembic.
revision = '57887b4ff41c'
down_revision = 'f5c963d13750'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
