"""added kathisma and psalm

Revision ID: 7869e756f33d
Revises: b4cff0b43d70
Create Date: 2016-09-14 15:15:53.732419

"""

# revision identifiers, used by Alembic.
revision = '7869e756f33d'
down_revision = 'b4cff0b43d70'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('kathismas',
    sa.Column('book_slug', sa.String(), nullable=False),
    sa.Column('kathisma_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.Text(), nullable=True),
    sa.Column('title_slavonic', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['book_slug'], ['books.book_slug'], ),
    sa.PrimaryKeyConstraint('book_slug', 'kathisma_id')
    )
    op.create_table('psalms',
    sa.Column('book_slug', sa.String(), nullable=False),
    sa.Column('kathisma_id', sa.Integer(), nullable=False),
    sa.Column('psalm_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.Text(), nullable=True),
    sa.Column('title_slavonic', sa.Text(), nullable=True),
    sa.Column('text', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['kathisma_id', 'book_slug'], ['kathismas.kathisma_id', 'kathismas.book_slug'], ),
    sa.PrimaryKeyConstraint('book_slug', 'kathisma_id', 'psalm_id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('psalms')
    op.drop_table('kathismas')
    ### end Alembic commands ###
