"""Added chapter text

Revision ID: 7ce18c6c101a
Revises: c1bcc61592ed
Create Date: 2016-08-18 18:45:15.805459

"""

# revision identifiers, used by Alembic.
revision = '7ce18c6c101a'
down_revision = 'c1bcc61592ed'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chapter_texts',
    sa.Column('book_slug', sa.String(), nullable=False),
    sa.Column('chapter_id', sa.Integer(), nullable=False),
    sa.Column('text', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['chapter_id', 'book_slug'], ['chapters.chapter_id', 'chapters.book_slug'], ),
    sa.PrimaryKeyConstraint('book_slug', 'chapter_id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('chapter_texts')
    ### end Alembic commands ###
