"""Added Chapter Text

Revision ID: 9b8c1c72b21b
Revises: e491d9fd382a
Create Date: 2016-09-14 12:32:25.366502

"""

# revision identifiers, used by Alembic.
revision = '9b8c1c72b21b'
down_revision = 'e491d9fd382a'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chapter_texts',
    sa.Column('book_slug', sa.String(), nullable=False),
    sa.Column('chapter_id', sa.Integer(), nullable=False),
    sa.Column('text', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['chapter_id', 'book_slug'], ['chapters.chapter_id', 'chapters.book_slug'], ),
    sa.PrimaryKeyConstraint('book_slug', 'chapter_id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('chapter_texts')
    ### end Alembic commands ###
