"""Added relationship(

Revision ID: b093dc677450
Revises: de34700df3ef
Create Date: 2016-09-15 17:07:22.118873

"""

# revision identifiers, used by Alembic.
revision = 'b093dc677450'
down_revision = 'de34700df3ef'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pericopes',
    sa.Column('chapter_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.Text(), nullable=True),
    sa.Column('title_slavonic', sa.Text(), nullable=True),
    sa.Column('text', sa.Text(), nullable=True),
    sa.Column('book_slug', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['book_slug'], ['books.book_slug'], ),
    sa.PrimaryKeyConstraint('chapter_id', 'book_slug')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('pericopes')
    ### end Alembic commands ###
