"""Remove title

Revision ID: b352683575b8
Revises: d01f7ce38c96
Create Date: 2016-08-16 08:50:51.757361

"""

# revision identifiers, used by Alembic.
revision = 'b352683575b8'
down_revision = 'd01f7ce38c96'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('chapters', 'title')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('chapters', 'title')
    ### end Alembic commands ###
