"""added book ending

Revision ID: b4cff0b43d70
Revises: c850b1db67e7
Create Date: 2016-09-14 13:52:34.185849

"""

# revision identifiers, used by Alembic.
revision = 'b4cff0b43d70'
down_revision = 'c850b1db67e7'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('books', sa.Column('book_ending', sa.Text(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('books', 'book_ending')
    ### end Alembic commands ###
