"""Added chapter title slzvonic

Revision ID: c074846534a2
Revises: 9b8c1c72b21b
Create Date: 2016-09-14 12:34:00.520089

"""

# revision identifiers, used by Alembic.
revision = 'c074846534a2'
down_revision = '9b8c1c72b21b'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chapters', sa.Column('title_slavonic', sa.Text(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('chapters', 'title_slavonic')
    ### end Alembic commands ###
