"""Added title_slavonic

Revision ID: c1bcc61592ed
Revises: e5367b93d93a
Create Date: 2016-08-18 13:40:52.824693

"""

# revision identifiers, used by Alembic.
revision = 'c1bcc61592ed'
down_revision = 'e5367b93d93a'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('books', sa.Column('title_slavonic', sa.Text(), nullable=True))
    op.add_column('chapters', sa.Column('title', sa.Text(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('chapters', 'title')
    op.drop_column('books', 'title_slavonic')
    ### end Alembic commands ###
