"""removed chapter text

Revision ID: c850b1db67e7
Revises: c074846534a2
Create Date: 2016-09-14 13:14:51.762161

"""

# revision identifiers, used by Alembic.
revision = 'c850b1db67e7'
down_revision = 'c074846534a2'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('chapter_texts')
    op.add_column('chapters', sa.Column('text', sa.Text(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('chapters', 'text')
    op.create_table('chapter_texts',
    sa.Column('book_slug', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('chapter_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('text', sa.TEXT(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['chapter_id', 'book_slug'], ['chapters.chapter_id', 'chapters.book_slug'], name='chapter_texts_chapter_id_fkey'),
    sa.PrimaryKeyConstraint('book_slug', 'chapter_id', name='chapter_texts_pkey')
    )
    ### end Alembic commands ###
