"""Add book_id

Revision ID: d01f7ce38c96
Revises: 0fef79a40a66
Create Date: 2016-08-13 15:56:16.787245

"""

# revision identifiers, used by Alembic.
revision = 'd01f7ce38c96'
down_revision = '0fef79a40a66'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('books', sa.Column('book_id', sa.Integer(), nullable=False))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('books', 'book_id')
    ### end Alembic commands ###
