"""Added in_bible_list

Revision ID: de34700df3ef
Revises: 7869e756f33d
Create Date: 2016-09-15 16:14:00.724169

"""

# revision identifiers, used by Alembic.
revision = 'de34700df3ef'
down_revision = '7869e756f33d'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('books', sa.Column('in_bible_list', sa.Boolean(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('books', 'in_bible_list')
    ### end Alembic commands ###
