"""Added book_id

Revision ID: e491d9fd382a
Revises: ee0d4ec906ac
Create Date: 2016-09-14 12:31:37.540448

"""

# revision identifiers, used by Alembic.
revision = 'e491d9fd382a'
down_revision = 'ee0d4ec906ac'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('books', sa.Column('book_id', sa.Integer(), nullable=False))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('books', 'book_id')
    ### end Alembic commands ###
