"""Initial

Revision ID: ee0d4ec906ac
Revises: 
Create Date: 2016-09-14 12:30:13.826057

"""

# revision identifiers, used by Alembic.
revision = 'ee0d4ec906ac'
down_revision = None
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('books',
    sa.Column('book_slug', sa.String(), nullable=False),
    sa.Column('title', sa.Text(), nullable=True),
    sa.Column('title_slavonic', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('book_slug')
    )
    op.create_table('chapters',
    sa.Column('book_slug', sa.String(), nullable=False),
    sa.Column('chapter_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['book_slug'], ['books.book_slug'], ),
    sa.PrimaryKeyConstraint('book_slug', 'chapter_id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('chapters')
    op.drop_table('books')
    ### end Alembic commands ###
