"""Added book id

Revision ID: fed0f415374b
Revises: 15204a4fbb42
Create Date: 2016-09-16 14:19:44.339047

"""

# revision identifiers, used by Alembic.
revision = 'fed0f415374b'
down_revision = '15204a4fbb42'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('books', sa.Column('id', sa.Integer(), nullable=False))
    op.add_column('chapters', sa.Column('text', sa.Text(), nullable=True))
    op.add_column('chapters', sa.Column('title_slavonic', sa.Text(), nullable=True))
    op.add_column('pericopes', sa.Column('text', sa.Text(), nullable=True))
    op.add_column('pericopes', sa.Column('title_slavonic', sa.Text(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('pericopes', 'title_slavonic')
    op.drop_column('pericopes', 'text')
    op.drop_column('chapters', 'title_slavonic')
    op.drop_column('chapters', 'text')
    op.drop_column('books', 'id')
    ### end Alembic commands ###
